In [32]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline 
import seaborn as sns

In [33]:
data = pd.read_csv('glass.csv')

In [34]:
data

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X171,X172,X173,X174,X175,X176,X177,X178,X179,X180
0,1,0.1,0.1,0.1,0.10,0.1,0.1,0.1,0.10,0.100,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
1,2,0.1,0.1,0.1,0.10,0.1,0.1,0.1,0.10,0.100,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
2,3,0.1,0.1,0.1,0.10,0.1,0.1,0.1,0.28,0.100,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
3,4,0.1,0.1,0.1,0.10,0.1,0.1,0.1,0.10,0.100,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
4,5,0.1,0.1,0.1,0.10,0.1,0.1,0.1,0.10,0.100,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,746,42.8,43.2,44.2,46.25,44.4,45.0,46.4,48.80,45.500,...,45.2,43.8,41.4,45.6,47.2,47.2,48.0,45.0,42.0,50.0
746,747,47.0,44.8,49.8,49.25,45.6,39.6,42.2,44.80,38.667,...,43.2,44.4,43.6,42.6,42.0,46.0,46.4,40.2,45.8,39.8
747,748,40.6,43.8,40.6,46.50,43.4,45.4,41.4,39.20,41.000,...,42.0,44.4,43.2,38.0,45.8,47.6,46.4,43.0,47.0,47.4
748,749,41.6,44.4,40.4,47.00,40.0,43.6,49.8,41.60,42.000,...,45.4,41.8,42.2,49.0,47.4,38.8,41.4,44.4,44.8,43.4
749,750,41.6,37.2,42.0,42.50,40.6,40.8,42.8,40.80,40.167,...,41.4,45.4,40.6,42.6,45.2,47.2,44.8,43.0,47.2,44.8

In [35]:
df = data.drop(['Unnamed: 0'],axis =1).T

# tranposed because there are 150 samples and 750 variables so the samples should be
# in the rows and the variables in the columns

In [36]:
df

,0,1,2,3,4,5,6,7,8,9,...,740,741,742,743,744,745,746,747,748,749
X1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,40.80,38.40,41.80,41.80,50.60,42.80,47.00,40.6,41.6,41.6
X2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,41.60,43.60,42.40,39.60,42.80,43.20,44.80,43.8,44.4,37.2
X3,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,50.60,41.00,45.60,47.80,47.00,44.20,49.80,40.6,40.4,42.0
X4,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,45.75,45.75,42.75,40.75,42.75,46.25,49.25,46.5,47.0,42.5
X5,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,42.20,41.40,39.60,44.80,43.00,44.40,45.60,43.4,40.0,40.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
X176,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,45.60,48.80,46.80,38.40,44.40,47.20,46.00,47.6,38.8,47.2
X177,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,42.80,42.80,42.60,37.80,45.80,48.00,46.40,46.4,41.4,44.8
X178,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,40.40,46.00,44.00,40.40,44.40,45.00,40.20,43.0,44.4,43.0
X179,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,45.40,43.00,39.20,43.20,44.00,42.00,45.80,47.0,44.8,47.2
X180,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,44.60,49.40,47.80,46.80,42.40,50.00,39.80,47.4,43.4,44.8

#### Stage 1 of Procedure 
**we need to perform svd on the mean centered data matrix and the paper states that it uses FAST EVD  Algorithm when p > n instead of using Standard SVD , we wont be doing that here since the code for that is available only in matlab and not python . First we mean center the data and then find the rank of this matrix = r0 , only the first r0 eigen values on the D matrix will be non zero rest will all be zero so we can take only r0 columns of D and similarly for U - r0 columns for V_tranpose - R0 rows**

In [37]:
A_centered = df.apply(lambda x : x- x.mean()).values
U,  D , V_transpose = np.linalg.svd(A_centered)
print(U.shape)
print(np.diag(D).shape)
print(V_transpose.shape)
## rank of matrix A = 180 since 180 non singular values in matrix D

(180, 180)
(180, 180)
(750, 750)

**now the new data matrix will be  = U(n x r0) into D(r0 x r0) and this will have n rows and r0 columns so it would have dimension 180 x 180** (r0 = 180)

In [38]:
new_data = pd.DataFrame(U @ np.diag(D))
new_data

,0,1,2,3,4,5,6,7,8,9,...,170,171,172,173,174,175,176,177,178,179
0,-643.394365,-1261.536996,-1007.689522,-391.399132,-37.856411,44.179959,-21.177200,111.689003,-161.116914,3.089894,...,-14.060890,4.509362,4.337819,-1.038457,-4.017068,3.536848,-4.419211,3.735043,-0.397029,-7.287806e-13
1,-876.085117,-1170.577585,-797.509268,-406.570755,-31.081244,45.352192,-20.196954,142.462006,-146.243233,-5.549599,...,-6.935078,-8.885383,-3.663759,-3.870948,-2.471774,5.458791,5.866991,-1.742078,-0.885669,-7.287806e-13
2,-2120.158267,-915.394061,-1782.294966,-477.116774,-54.877514,79.209359,36.634634,194.369397,-48.542472,93.103459,...,-4.841204,2.429976,-3.578824,3.691980,-0.702671,1.147848,-8.252406,-0.113460,7.256665,-7.287806e-13
3,-1892.409055,-932.920097,-1696.399889,-476.649776,-65.187677,87.331380,64.293939,217.131191,-63.132132,15.874870,...,0.457208,2.168138,-2.094306,-0.929319,6.848451,2.526009,1.191795,-2.723430,5.628091,-7.287806e-13
4,-220.176043,-1531.676132,-1305.370337,-361.224431,-39.176116,20.554130,96.782139,33.583611,-200.640681,-23.623076,...,5.718653,4.211983,-2.561158,2.021978,3.700083,-6.711216,6.293983,2.904810,-6.801610,-7.287806e-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,7027.912512,2081.980796,727.632092,-2.111297,202.270368,-260.181329,-186.077443,27.543309,-112.247155,228.405549,...,-2.778019,-7.555122,1.017886,0.655195,4.242261,1.740941,-2.796822,-0.531054,-11.788300,-7.287806e-13
176,7004.520851,2078.850994,790.096059,-34.150916,224.818655,-276.110802,-209.704816,9.965667,-93.115223,250.280878,...,-0.587986,1.147435,0.099264,-4.273499,-2.910368,-5.038262,-2.573102,-8.656500,6.732630,-7.287806e-13
177,7381.186386,-481.381465,305.816849,-216.506554,76.763853,-140.550935,-355.112810,58.778025,2.115773,-0.189697,...,3.885221,2.632126,2.707081,-5.087123,-1.494672,1.859306,-0.871905,-0.128773,3.461317,-7.287806e-13
178,6769.102579,1619.324403,312.999384,-81.236870,180.165256,-247.945218,-149.885846,72.154048,-87.903709,167.463598,...,-1.905651,-2.960547,1.101919,2.301958,-6.770077,5.042446,4.301168,7.013644,0.705996,-7.287806e-13
179,3276.449641,2499.697187,-1311.145464,-244.767728,154.875441,-377.917212,137.310424,167.730285,190.526577,210.722681,...,1.685101,3.509963,-2.181901,-0.021319,3.590500,5.587772,-0.828033,-2.678312,-1.111384,-7.287806e-13

#### STAGE 2 - Finding "h" < n  least outlying data points using the Stahel-Donoho estimator
like in the paper h = 0.7*n = 126

**To find the least outlying data points we use the projection pursuit principle : Multivariate Outlier should be outlier in atleast one direction but not necessarily the direction of the coordinate axes**


**So we consider a set B of the directions to project along and then we project all the datapoints onto a particular vector $v \in B$  and now for every datapoint we use the Stahel-Donoho measure to  quantify how "outlying" the data point is in direction v . We find this measure of "outlyingness"  $\forall v \in B$ and the measure of "outlyingness" for a data point  $x_{i}$ is the maximum of this value over all directions in B**


**B consists of 250 vectors which are linear combinations of any two data points**

In [39]:
### function to get the set B -- set of random directions to project 
## 250 Directions each of them are obatained from 2 randomnly sampled points from the data set 
def get_Directions(X,seed):
    mat = np.zeros((250,X.shape[1]))
    for i in range(250):
        np.random.seed(seed+i)
        random_points = np.random.choice(X.shape[0], 2, replace=False)
        mat[i,:] = X.iloc[random_points[0],:] - X.iloc[random_points[1],:]
    return pd.DataFrame(mat)
B = get_Directions(new_data,0)

In [43]:
from sklearn.covariance import MinCovDet
## now we need to project all the datapoints and find the Stahel-Donoho measure for each observation
def get_OutlierScores(X,h = 0.7):
    B = get_Directions(X,0)
    temp = np.sqrt(np.square(X).sum(axis=1)) ## finding norm of each row in B ( IE direction)
    ## since we want non zero B we must remove those vectors with zero norm 
    B_reduced = B[temp > 1e-12]
    temp2 = temp[temp > 1e-12]
    projections = X @ np.transpose(np.diag(1/temp2) @ B_reduced)
    Outlyingness = np.zeros((X.shape[0],len(temp2)))## collect outlyingness of each point in the non zero directions
    for i in range(len(temp2)):
        x = projections[:,i]
        cov = MinCovDet(random_state=0,support_fraction= h).fit(np.array(x).reshape(-1,1))
        Outlyingness[:,i] = abs(projections[:,i]-cov.location_)/np.sqrt(cov.covariance_)
    Outlying_scores = np.amax(Outlyingness,axis=1)
    return Outlying_scores

In [53]:
x = [1,2,3,4,5,5,6,6,34,45,4455,23,32,21,1,1,1,1,333333,555664,2233454,4,3,3,3,3,32222222]
cov = MinCovDet(random_state=0,support_fraction=0.7).fit(np.array(x).reshape(-1,1))
print(cov.location_)
print(np.sqrt(cov.covariance_))
print(np.mean(x))
print(np.std(x))

[9.40909091]
[[12.49603243]]
1309234.6296296297
6077887.14230229